import numpy as np
from typing import Optional

class ModelAPI:
    name: str
    def fit(self, X: np.ndarray, y: Optional[np.ndarray], **kwargs): ...
    def predict(self, X: np.ndarray) -> np.ndarray: ...
    def predict_proba(self, X: np.ndarray) -> np.ndarray: ...
    def save(self, path: str) -> None: ...
    @classmethod
    def load(cls, path: str): ...
